#!/bin/bash
#
# dist_fedora
# Copyright 2013 Zandre Bran (abrandao@students.ic.unicamp.br)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

REPO_COMMAND="yum"
REPO_INSTALL="install"
REPO_REMOVE="remove"
REPO_UPDATE="update"
REPO_YES="-y"

PACKAGES_EA_INSTALL=""
PACKAGES_EA_REMOVE=""
PACKAGES_EA_BLOCKUPDATES=""

