#!/bin/bash
#
# espirito-acessibilidade 
# Copyright 2013 Zandre Bran (abrandao@students.ic.unicamp.br)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License 
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

#yum -y install lynx links elinks xpdf screen xclip clpbar mutt wget mc newsbeuter sylpheed mplayer emacs epiphany

if [ $(echo $PATH | grep $MYSELF | wc -l) -eq 0 ]
then
echo """
EA_DIR=$HOME/$MYSELF/
PATH=$PATH:$HOME/$MYSELF/
export PATH""" >> $HOME/.bash_profile
. $HOME/.bash_profile
fi

chmod -R 755 $EA_DIR

if [ -s $LANG ] 
then
exit 1
fi

/bin/bash ${EA_DIR}lang_$( echo $LANG | awk -F "." {' print $1 '} | tr [A-Z] [a-z] )

if [ $? -ne 0 ]
then
    # padrão
    ${EA_DIR}lang_pt_br
fi

# backup dconf - only first time
#====================================================================
ls ${EA_DIR}gsettings_backup &>/dev/null || dconf dump / > ${EA_DIR}gsettings_backup
# recovery backup
# dconf load / < ${EA_DIR}settings_backup

# settings
#====================================================================
/bin/bash ${EA_DIR}settings
wait

# KEYBINDS
#====================================================================
/bin/bash ${EA_DIR}keybinds --install
wait

# END
#====================================================================

#FIXME arquivo de tradução
spd-say $EA_CONCLUIDO

