#!/bin/bash
#
# espirito-acessibilidade 
# Copyright 2013 Zandre Bran (abrandao@students.ic.unicamp.br)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

chmod -R 755 $HOME/espirito-acessibilidade/

if [ $(echo $PATH | grep "espirito-acessibilidade" | wc -l) -eq 0 ]
then
echo """
PATH=$PATH:$HOME/espirito-acessibilidade/
export PATH""" >> $HOME/.bash_profile
#FIXME ubuntu tb é no .bash_profile??
. $HOME/.bash_profile
fi

# settings
#====================================================================
bash settings
wait

# KEYBINDS
#====================================================================
bash keybinds --install
wait

# FIM
#====================================================================

#FIXME arquivo de tradução
spd-say "Programa espirito acessibilidade concluído."

