#!/bin/bash
#
# keybinds 
# Copyright 2013 Zandre Bran (abrandao@students.ic.unicamp.br)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>
#
#http://www.linuxacessivel.org/documentos/teclas-de-atalho/teclas-especiais-do-sistema/

# CTRL+ALT+K (custom0) - "grilo -r"
# <Alt>Page_Up (custom1) - "aumenta o som"
# <Alt>Page_Down (custom2) - "diminue o som"

function f_setkey () {

#====================================================================
# CTRL+ALT+K (custom0) - "grilo -r"
gsettings set org.gnome.settings-daemon.plugins.media-keys \
custom-keybindings \
"['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
name "Reinicia sistema de audio e acessibilidade"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
command "${EA_DIR}grilo -r"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
binding "<Primary><Alt>K"

# ===================================================================
# <Alt>Page_Up (custom1) - "aumenta o som"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
custom-keybindings \
"['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ \
name "Aumenta volume do audio"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ \
command "${EA_DIR}grilo +"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ \
binding "<Alt>Page_Up"

# ===================================================================
# <Alt>Page_Down (custom2) - "diminue o som"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
custom-keybindings \
"['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ \
name "Diminue volume do audio"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ \
command "${EA_DIR}grilo -"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ \
binding "<Alt>Page_Down"

# ===================================================================
# <Alt>End (custom3) - "liga|delisga som"

gsettings set org.gnome.settings-daemon.plugins.media-keys \
custom-keybindings \
"['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/']"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ \
name "Liga ou Desliga audio"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ \
command "amixer sset Master toggle"

gsettings set \
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ \
binding "<Alt>End"
}

case "$1" in
"")
#TODO
echo "Usage: keybinds [-l | --list] [-i | --install]"
exit 1
;;

-l | --list)
#TODO exibe a lista de todos os atalhos
;;

-h | --help)
#TODO 
exit 0
;;

-i | --install)
f_setkey
exit 0
;;
esac
